Parameterize fuzz test scripts

diff --git a/t/fuzz/qname b/t/fuzz/qname
--- a/t/fuzz/qname
+++ b/t/fuzz/qname
@@ -1,8 +1,9 @@
 #!/bin/bash
 set -eu
+NAME=qname
 
-if [[ ! -x t/fuzz/r/qname ]]; then
-	echo >&2 "Fuzz Test runner 't/fuzz/r/qname' not found..."
+if [[ ! -x t/fuzz/r/${NAME} ]]; then
+	echo >&2 "Fuzz Test runner 't/fuzz/r/${NAME}' not found..."
 	echo >&2 "Do you need to run \`make fuzz-tests\`?"
 	exit 1
 fi
@@ -18,4 +19,4 @@ fi
 
 rm -rf t/fuzz/findings/
 set -x
-afl-fuzz -i t/fuzz/cases/qname -o t/fuzz/findings ./qname
+afl-fuzz -i t/fuzz/cases/${NAME} -o t/fuzz/findings t/fuzz/r/${NAME}
